version: '3'

services:
  nextjs-app:
    container_name: teaprapancha-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6892:3000'
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - "traefik.http.routers.teaprapancha.rule=Host(`teaprapancha.in`)"
      - traefik.http.routers.teaprapancha.entrypoints=http,https
      - traefik.http.routers.teaprapancha.tls.certresolver=letsencrypt
      - traefik.http.services.teaprapancha.loadbalancer.server.port=3000

networks:
  coolify:
    external: true
